[package]
name = "rust-chat-server-async-std"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.0"

[dependencies.async-std]
version = "1.7.0"
features = ["attributes"]
